name: chemvae_py37
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - ipykernel
  - matplotlib
  - pandas
  - pip
  - pip:
      - h5py
      - numpy
      - pyyaml
      - rdkit
      - rdkit-pypi
      - torchsummary
      - scikit-learn
